### PR TITLE
JUnit 4.10 modifications

### PR DESCRIPTION
**Pull request by elfrucool**
Hi

I modified the code to support JUnit 4.10.

Why? Because I want to use this wonderful library to build [Atlassian](https://developer.atlassian.com/confdev) plugins; and Atlassian SDK only supports JUnit 4.10.

Most important changes are:
* I created the branch based on tag r4.11.3 and since it is specific for JUnit 4.10 it may be useful that this change lives in its own branch
* Using JUnit 4.10 instead of 4.11, also using Hamcrest 1.1 instead of 1.3
* In JUnit 4.10, @Rule is not supported in methods (this caused compilation errors), so I removed the use of @Rule in methods.
* JUnit 4.10 uses Hamcrest 1.1; some matchers used in tests are missing, so I created them (fortunately they are few)
* Removed a few warnings

### CODE REVIEW

**Comment by elfrucool** [comment]
in order to merge this change, it is important to have a branch specific to JUnit 4.12

**Comment by mouyang** [comment]
Hi, 

I saw this while browsing this repository (since I am looking for a new master release), and I have a comments that you may want to consider.  I'm not a part of this project and @bechte will make the final decision as the project owner, but I hope my feedback may increase your chance of approval.

1. You're correct in needing a separate 4.10 branch, but merging this PR to master probably won't be accepted.  master is currently on r4.12.  If for any reason a project cannot upgrade from r4.10 to r4.12 (ie the project can only be upgraded to r4.11), then the project will lose all of the r4.12 functionality and experience regression.  You were also correcting in basing your initial work off the latest r4.11 point release (because this project has the requirement of using the latest point release for each supported JUnit version), and it would be perfectly fine to merge to a new branch for based off the latest r4.11 (instead of master) because upgrading from r4.10 to r4.11 would not result in regression.
1. As you've stated, you really need a new r4.10 branch.  There's a better chance of getting that by opening a new issue.  This way, you can have the PR merge to the r4.10 (not master) branch after it's been created.
1. Have you tried keeping the Hamcrest 1.3 dependency?  While JUnit 4.10 uses 1.1, I can't imagine it would be impossible to fix up the pom.xml so that it works with 1.3.  This would shrink the PR substantially if you are successful in doing so because CollectionMatchers would go away.  Keep in mind that introducing r4.10 support also introduces r4.10 maintenance.  If I were maintaining this library, I would not want to maintain CollectionMatchers if I didn't have to + I wouldn't have to if I kept the Hamcrest 1.3 dependency.  Porting fixes in r4.10 to later versions would also be significantly easier if CollectionMatchers wasn't there.

Those are my thoughts.  You've presented a good case for JUnit 4.10 support and it's great that you took the initiative on this.  Best of luck.

Matt

**Comment by bechte** [comment]
Is there still a need for the JUnit Version 4.10 to be supported? I never tested the runner with versions of JUnit prior to 4.11. Therefore, I cannot guarantee that it will work with 4.10. I believe it is no longer required?

**Comment by mouyang** [comment]
@elfrucool would be the best person to comment on whether JUnit 4.10 support is still needed.  I only made a comment to discuss the possibility of simplifying the PR.

**Comment by elfrucool** [comment]
Hi

I needed 4.10 support for a project on Atlassian platform I was working on
2017, I no longer work on that project anymore and I don't know if
Atlassian upgraded supported JUnit version since then.

So, I personally no longer need 4.10 support

Best regards

**Pull request closed without merging**
